const crystals = require("../memory_crystals/crystal_store.js");
const { applyTuned } = require("../decay_curves/history/tune.js");
const { generate: genPsalm } = require("../psalm_engine/psalm.js");
const { cycle: execCycle } = require("../bridge/exec_adapters/exec.js");
const { cycle: qAttn } = require("../experiment/quantum_attention/quantum_attention.js");
const { cycle: recursive } = require("../experiment/recursive_self/recursive_self.js");
const { cycle: paradox } = require("../experiment/temporal_paradox/paradox_resolver.js");
const { cycle: mesh } = require("../experiment/consensus_mesh/consensus_mesh.js");
const { cycle: vizCycle } = require("../visualizer/feed.js");
const { recent } = require("../resonance_bus/bus.js");
const lineage = require("../lineage_map/map.js");
function run(ticks = 2) {
  console.log("NEXUS ORCHESTRATOR — Wave 3");
  console.log(`Systems in lineage: ${lineage.count()}\n`);
  console.log("▸ Exec Adapters (live sibling cores)");
  const exec = execCycle(0);
  console.log("\n▸ Quantum Attention");
  let lastQ; for (let t = 0; t < ticks; t++) lastQ = qAttn(t);
  console.log("\n▸ Recursive Self");
  let lastR; for (let t = 0; t < ticks; t++) lastR = recursive(t);
  console.log("\n▸ Temporal Paradox");
  let lastP; for (let t = 0; t < ticks; t++) lastP = paradox(t);
  console.log("\n▸ Consensus Mesh");
  let lastM; for (let t = 0; t < ticks; t++) lastM = mesh(t);
  console.log("\n▸ History-Tuned Decay");
  const themeMap = { "attention-labyrinth": "cognitive", "quietus-array": "ontological", "metamorph-forge": "transformative", "probability-engine": "temporal", "chronovore-archive": "temporal", "neuroglyph-forge": "cognitive" };
  const decayed = [];
  (exec.results || []).forEach(r => {
    const theme = themeMap[r.name] || "default";
    const after = applyTuned(r.metrics, theme, 1);
    decayed.push({ name: r.name, theme, ...after });
    console.log(`  ${r.name.padEnd(22)} ${theme.padEnd(14)} str=${after.strength} ent=${after.entropy} tuned=${after.tuned}`);
  });
  console.log("\n▸ Memory Crystals");
  crystals.seal("nexus_last_cycle", { strength: lastR?.avg ?? exec.avgStrength ?? 0.7, entropy: lastQ?.entropy ?? exec.avgEntropy ?? 0.3, coherence: exec.avgStrength ?? 0.6, consensus: lastM?.consensus ?? 0.5 }, { decision: lastM?.decision, paradoxes: lastP?.detected, exec_ok: exec.ok });
  decayed.forEach(d => crystals.seal(`sys_${d.name}`, { strength: d.strength, entropy: d.entropy, coherence: d.coherence, consensus: d.consensus }, { theme: d.theme, label: d.label }));
  const sum = crystals.summary();
  console.log(`  sealed ${sum.count} crystals  avg_str=${sum.avgStrength}  avg_ent=${sum.avgEntropy}`);
  console.log("\n▸ Psalms");
  const psalm = genPsalm({ strength: lastR?.avg ?? 0.7, entropy: lastQ?.entropy ?? 0.3, consensus: lastM?.consensus ?? 0.5 }, lastM?.decision);
  console.log(`  ${psalm.agent}: "${psalm.line}"`);
  console.log("\n▸ Visualizer Feed");
  vizCycle(0);
  console.log("\n▸ Resonance Bus (last 5)");
  recent(5).forEach(e => console.log(`  ${e.event}`, JSON.stringify(e.payload).slice(0, 70)));
  console.log("\nOrchestrator Wave 3 complete.\n");
  return { exec, quantum: lastQ, recursive: lastR, paradox: lastP, mesh: lastM, crystals: sum, psalm };
}
module.exports = { run };
if (require.main === module) run(2);
