const crystals = require("../memory_crystals/crystal_store.js");
const { applyTuned } = require("../decay_curves/history/tune.js");
const { inject } = require("../psalm_engine/inject/inject.js");
const { cycle: execCycle, available } = require("../bridge/exec_adapters/exec.js");
const { cycle: qAttn } = require("../experiment/quantum_attention/quantum_attention.js");
const { cycle: recursive } = require("../experiment/recursive_self/recursive_self.js");
const { cycle: paradox } = require("../experiment/temporal_paradox/paradox_resolver.js");
const { cycle: mesh } = require("../experiment/consensus_mesh/consensus_mesh.js");
const { cycle: vizCycle } = require("../visualizer/feed.js");
const { recent } = require("../resonance_bus/bus.js");
const lineage = require("../lineage_map/map.js");
const { writeReport } = require("../reports/report.js");
const { exportFrame } = require("../metrics_export/export.js");
const oracle = require("../experiment/oracle_die/oracle.js");
const dream = require("../experiment/dream_buffer/dream_buffer.js");
const tide = require("../experiment/tide_clock/tide.js");
const liminal = require("../experiment/liminal_gate/gate.js");
const myth = require("../experiment/myth_weaver/myth.js");
const dissonance = require("../experiment/choir_dissonance/dissonance.js");
const archaeology = require("../experiment/echo_archaeology/archaeology.js");
const compost = require("../experiment/collapse_compost/compost.js");
function run(ticks = 2) {
  console.log("NEXUS ORCHESTRATOR — Wave 5\n");
  const subset = available().slice(0, 8);
  console.log("▸ Exec"); const exec = execCycle(0, subset);
  console.log("\n▸ Quantum"); let lastQ; for (let t = 0; t < ticks; t++) lastQ = qAttn(t);
  console.log("\n▸ Recursive"); let lastR; for (let t = 0; t < ticks; t++) lastR = recursive(t);
  console.log("\n▸ Paradox"); let lastP; for (let t = 0; t < ticks; t++) lastP = paradox(t);
  console.log("\n▸ Archaeology → Compost");
  const ghosts = []; for (let t = 0; t < 2; t++) ghosts.push(archaeology.cycle(t));
  const composted = compost.enrich({ strength: exec.avgStrength, entropy: exec.avgEntropy, coherence: 0.6, consensus: 0.55 }, compost.compost(ghosts.map(g => ({ fragment: g.strength, source: g.source }))));
  console.log(`  harvested=${composted.harvest.harvested}`);
  console.log("\n▸ Oracle"); const face = oracle.cast(); console.log(`  ${face.name}: "${face.omen}"`);
  console.log("\n▸ Tide"); const tideState = tide.cycle(0);
  console.log("\n▸ Dream"); dream.dream("nexus", { strength: exec.avgStrength, entropy: exec.avgEntropy }, 0.3);
  const contaminated = dream.contaminate({ strength: exec.avgStrength, entropy: exec.avgEntropy, coherence: exec.avgStrength * 0.9, consensus: 0.6 }, 0.2);
  console.log(`  str=${contaminated.strength.toFixed(3)}`);
  console.log("\n▸ Liminal"); liminal.reset(); liminal.check({ strength: contaminated.strength });
  const lim = liminal.check({ strength: Math.min(0.99, contaminated.strength * tideState.tide) });
  console.log(`  side=${lim.side}`);
  console.log("\n▸ Dissonance");
  const nodes = (exec.results || []).slice(0, 4).map(r => ({ id: r.name.split("-")[0], strength: r.metrics.strength, entropy: r.metrics.entropy }));
  let dissentResult = nodes.length >= 2 ? dissonance.dissent(nodes) : null;
  if (dissentResult) console.log(`  ${dissentResult.dissenter} → ${dissentResult.decision}`);
  console.log("\n▸ Mesh"); let lastM; for (let t = 0; t < ticks; t++) lastM = mesh(t);
  if (lastM && face.bias?.consensus) lastM = { ...lastM, consensus: Math.max(0, Math.min(1, lastM.consensus + face.bias.consensus)) };
  console.log("\n▸ Decay + Tide");
  const decayed = [];
  (exec.results || []).forEach(r => {
    let m = applyTuned(r.metrics, r.theme || "default", 1);
    const tuned = m.tuned; m = tide.apply(m, 0); m.tuned = tuned;
    decayed.push({ name: r.name, theme: r.theme, ...m });
    console.log(`  ${r.name.padEnd(26)} str=${(+m.strength).toFixed(3)}`);
  });
  console.log("\n▸ Crystals");
  crystals.seal("nexus_last_cycle", { strength: lastR?.avg ?? contaminated.strength, entropy: lastQ?.entropy ?? contaminated.entropy, coherence: contaminated.coherence, consensus: lastM?.consensus ?? 0.5 }, { decision: lastM?.decision, oracle: face.name, wave: "5-report" });
  decayed.forEach(d => crystals.seal(`sys_${d.name}`, { strength: d.strength, entropy: d.entropy, coherence: d.coherence, consensus: d.consensus }, { theme: d.theme }));
  const sum = crystals.summary();
  console.log(`  total=${sum.count}`);
  console.log("\n▸ Psalm"); const psalm = inject({ strength: lastR?.avg ?? 0.7, entropy: lastQ?.entropy ?? 0.3, consensus: lastM?.consensus ?? 0.5 }, lastM?.decision);
  console.log("\n▸ Myth"); const lastMyth = myth.cycle(0);
  console.log("\n▸ Export + Viz");
  exportFrame((exec.results || []).map(r => ({ label: r.name, metrics: r.metrics, theme: r.theme })), { decision: lastM?.decision, oracle: face.name, consensus: lastM?.consensus, wave: "5-report" });
  vizCycle(0);
  console.log("\n▸ Report");
  writeReport({ lineage: lineage.count(), exec, mesh: lastM, oracle: face, crystals: sum, psalm, creative: { liminal: lim.side, dissent: dissentResult?.dissenter, myth: lastMyth?.title, compost_harvested: composted.harvest.harvested } });
  console.log("\n▸ Bus"); recent(5).forEach(e => console.log(`  ${e.event}`));
  console.log("\nWave 5 complete.\n");
  return { exec, mesh: lastM, crystals: sum, psalm, oracle: face };
}
module.exports = { run };
if (require.main === module) run(2);
